package entity.alumnos;
// Generated 19-nov-2018 22:51:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private int asg;
     private String nombre;
     private Integer ct;
     private Integer cp;
     private Set matriculas = new HashSet(0);

    public Asignatura() {
    }

	
    public Asignatura(int asg) {
        this.asg = asg;
    }
    public Asignatura(int asg, String nombre, Integer ct, Integer cp, Set matriculas) {
       this.asg = asg;
       this.nombre = nombre;
       this.ct = ct;
       this.cp = cp;
       this.matriculas = matriculas;
    }
   
    public int getAsg() {
        return this.asg;
    }
    
    public void setAsg(int asg) {
        this.asg = asg;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getCt() {
        return this.ct;
    }
    
    public void setCt(Integer ct) {
        this.ct = ct;
    }
    public Integer getCp() {
        return this.cp;
    }
    
    public void setCp(Integer cp) {
        this.cp = cp;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


