package entity.alumnos;
// Generated 19-nov-2018 22:51:26 by Hibernate Tools 4.3.1



/**
 * MatriculaId generated by hbm2java
 */
public class MatriculaId  implements java.io.Serializable {


     private String dni;
     private int asg;

    public MatriculaId() {
    }

    public MatriculaId(String dni, int asg) {
       this.dni = dni;
       this.asg = asg;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public int getAsg() {
        return this.asg;
    }
    
    public void setAsg(int asg) {
        this.asg = asg;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculaId) ) return false;
		 MatriculaId castOther = ( MatriculaId ) other; 
         
		 return ( (this.getDni()==castOther.getDni()) || ( this.getDni()!=null && castOther.getDni()!=null && this.getDni().equals(castOther.getDni()) ) )
 && (this.getAsg()==castOther.getAsg());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDni() == null ? 0 : this.getDni().hashCode() );
         result = 37 * result + this.getAsg();
         return result;
   }   


}


